### ISSUE TITLE
Find new home for status-bot

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/status-bot#4]
The status bot is currently running on my Raspberry Pi at home, it would be preferable to move it somewhere else, like a public cloud provider. 

@harsha5500 Maybe it could run on your Linode instance? Has to be outside kthcloud as otherwise it would go down with it and wouldn't be able to report outages

**Comment by harsha5500** [comment]
Sure! I can host it. I will create a user for the cloud and share the ip address for a DNS entry

**Comment by pierrelefevre** [comment]
> Sure! I can host it. I will create a user for the cloud and share the ip address for a DNS entry

The status bot doesn't need any access from the outside, it's just pinging and posting to Mastodon and Bluesky, so should be fine! 

I have a small shell script which I put in my copy of the status-bot repo on my laptop: 

```sh
rm -rf __pycache__
scp -P <pi_port> * <pi_host>:/home/pi/kthcloud-status
ssh <pi_host> docker compose -f /home/pi/kthcloud-status/compose.yml up -d --build 
```

Could probably be a cron job fetching github but it was more work 😅

**Comment by harsha5500** [comment]
Sure. We can create the script and host it today.
