### ISSUE TITLE
Update the endpoints

### ISSUE THREAD

**Issue by harsha5500** [kthcloud/status-bot#7]
Some of the endpoints are not there anymore in the new KTHCloud.

- https://k8s.cloud.cbh.kth.se
- https://k8s.prod.cloud.cbh.kth.se
- https://k8s.dev.cloud.cbh.kth.se
- https://se-flem-probe.app.cloud.cbh.kth.se
- https://se-kista-probe.app.kista.cloud/

Some of the other services should probably be managed by individual users. Or do we want a publish service which collects and toots based on the service.

- https://taiga.prod.cloud.cbh.kth.se

**Comment by harsha5500** [comment]
I had to take emergency action and I have removed the above mentioned CSV. If this is acceptable then we can close this issue. 
We should add the dancer to this list if possible.

**Comment by pierrelefevre** [comment]
These should definitely stay:

https://se-flem-probe.app.cloud.cbh.kth.se/
https://se-kista-probe.app.kista.cloud/

See https://github.com/kthcloud/go-deploy/issues/673 for why Kista is down

**Comment by pierrelefevre** [comment]
+1 for taiga not being our problem :)

**Comment by harsha5500** [comment]
Completed. But pushed directly to main branch.
